version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pennywise
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - pennywise-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: pennywise
      JWT_SECRET: your_jwt_secret_here
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pennywise-net

networks:
  pennywise-net:

    # volumes:
    #   db_data:
